sudo: required

language: python

python:
  - '3.10-dev'

before_script:
  - psql -c "CREATE DATABASE home_credit_api;" -U postgres
  - pip install -r requirements.txt
  - cd home_caredit_api
  - python manage.py migrate

branches:
  only:
    - staging

env:
  - DJANGO_SETTINGS_MODULE="home_credit_api.settings.travis"
  - DATABASE_URL=postgres://postgres@localhost/home_credit_api

services:
  - postgresql

script:
  - cd home_caredit_api
  - python manage.py test
