sudo: required

language: python

python:
  - '3.9'

before_script:
  - psql -c 'CREATE DATABASE home_credit_api;' -U postgres
  - pip install -r requirements.txt

branches:
  only:
    - staging

env:
  - DJANGO_SETTINGS_MODULE="home_credit_api.settings.travis"

services:
  - postgresql

script:
  - cd home_credit_api
  - python manage.py test
