# Generated by Django 4.1.7 on 2023-03-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimator',
            fields=[
                ('identifier', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('classifier', models.FileField(blank=True, upload_to='classifiers/')),
                ('shap_values', models.FileField(blank=True, upload_to='shap_values/')),
                ('columns_train', models.JSONField()),
                ('metrics', models.JSONField()),
                ('auc_conf_image', models.ImageField(blank=True, upload_to='plots/')),
                ('summary_image', models.ImageField(blank=True, upload_to='plots/')),
            ],
        ),
    ]
