# name: CI

# on:
#   push:
#     branches: [ staging ]
#   pull_request:
#     branches: [ staging ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:13
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: postgres
#           POSTGRES_HOST_AUTH_METHOD: trust
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.10.10
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.10.10
#     - name: Create PostgreSQL database
#       run: |
#         sudo -u postgres psql -c "CREATE DATABASE home_credit_api;"
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Create database
#       run: |
#         python home_credit_api/manage.py migrate --noinput
#     - name: Run tests
#       run: |
#         python home_credit_api/manage.py test
