name: CI

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

env:
  DB_ENGINE: django.db.backends.postgresql
  DB_NAME: home_credit_api_test
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: localhost
  DB_PORT: 5432

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Wait for database
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done
    - name: Create test database
      run: |
        createdb -h localhost -p 5432 -U postgres home_credit_api_test
    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: home_credit_api.settings
      run: |
        cd home_credit_api && python manage.py test
